import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:cli_util/cli_util.dart' as cli_util;
import 'package:interactive/src/utils.dart';
import 'package:interactive/src/vm_service_wrapper.dart';
import 'package:interactive/src/workspace_file_tree.dart';
import 'package:path/path.dart' as p;
import 'package:vm_service/vm_service.dart' as vm_service;

class WorkspaceIsolate {
  final VmServiceWrapper vm;
  final Process process;
  final String isolateId;
  bool _disposed = false;

  WorkspaceIsolate._({
    required this.vm,
    required this.process,
    required this.isolateId,
  }) {
    unawaited(
      process.exitCode.then((code) {
        if (!_disposed) {
          exit(code);
        }
      }),
    );
  }

  static Future<WorkspaceIsolate> create(
    WorkspaceFileTree workspaceFileTree,
  ) async {
    // Run pub get so that the package_config.json is generated and packages
    // are resolved correctly in the interpreter
    await _runPubGet(workingDirectory: workspaceFileTree.directory);

    final packageConfigFile = File(workspaceFileTree.pathPackageConfig);
    assert(
      packageConfigFile.existsSync(),
      'package_config.json does not exist at ${packageConfigFile.parent.path}',
    );

    final serviceInfoFile = File(
      p.join(workspaceFileTree.directory, '.dart_tool', 'vm_service_info.json'),
    );
    if (serviceInfoFile.existsSync()) {
      serviceInfoFile.deleteSync();
    }

    final process = await Process.start(
      _dartExecutable,
      [
        '--enable-vm-service=0',
        '--disable-service-auth-codes',
        '--no-dds',
        '--no-serve-devtools',
        '-DSILENT_OBSERVATORY=true',
        '--write-service-info=${serviceInfoFile.path}',
        '--packages=${workspaceFileTree.pathPackageConfig}',
        workspaceFileTree.pathAutoGeneratedDart,
      ],
      workingDirectory: workspaceFileTree.directory,
    );
    process.stdout.listen(stdout.add);
    process.stderr.listen(stderr.add);

    final serverUri = await _waitForServiceUri(serviceInfoFile, process);
    final vm = await VmServiceWrapper.create(serverUri);
    final isolateId = await _waitForMainIsolateId(vm);

    return WorkspaceIsolate._(vm: vm, process: process, isolateId: isolateId);
  }

  Future<vm_service.Isolate> get isolateInfo =>
      vm.vmService.getIsolate(isolateId);

  void dispose() {
    _disposed = true;
    process.kill();
    vm.dispose();
  }
}

String get _dartExecutable =>
    cli_util.dartExecutable ?? (Platform.isWindows ? 'dart.exe' : 'dart');

Future<String> _waitForMainIsolateId(VmServiceWrapper vm) async {
  while (true) {
    final isolates = (await vm.vmService.getVM()).isolates;
    if (isolates != null && isolates.isNotEmpty) {
      final isolateId = isolates.first.id;
      if (isolateId != null) {
        final isolate = await vm.vmService.getIsolate(isolateId);
        if (isolate.rootLib != null) {
          return isolateId;
        }
      }
    }
    await Future<void>.delayed(const Duration(milliseconds: 20));
  }
}

Future<Uri> _waitForServiceUri(File serviceInfoFile, Process process) async {
  int? exitCode;
  unawaited(process.exitCode.then((code) => exitCode = code));

  while (true) {
    if (serviceInfoFile.existsSync()) {
      try {
        final content = serviceInfoFile.readAsStringSync().trim();
        if (content.isNotEmpty) {
          final json = jsonDecode(content) as Map<String, dynamic>;
          final uriString = json['uri'] as String?;
          if (uriString != null) {
            return Uri.parse(uriString);
          }
        }
      } on FormatException {
        // Ignore partial writes while the child VM is flushing the file.
      }
    }
    if (exitCode != null) {
      throw StateError(
        'Child Dart VM process exited with code $exitCode before starting VM service.',
      );
    }
    await Future<void>.delayed(const Duration(milliseconds: 20));
  }
}

Future<void> _runPubGet({required String workingDirectory}) async {
  final cmd = getCrossPlatformCommand('$_dartExecutable pub get');

  final process = await Process.start(
    cmd.executable,
    cmd.arguments,
    workingDirectory: workingDirectory,
    runInShell: true,
  );

  final code = await process.exitCode;

  if (code != 0) {
    throw Exception(
        "pub get at '$workingDirectory' failed with exit code $code");
  }
}
