name: interactive
description: REPL (interactive shell) for Dart, supporting 3rd party packages, hot reload, and full grammar
version: 1.2.1
repository: https://github.com/fzyzcjy/flutter_interactive

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ^5.0.0
  args: ^2.3.1
  cli_repl: ^0.2.3
  collection: ^1.17.0
  logging: ^1.1.0
  path: ^1.8.2
  vm_service: ">=9.0.0 <12.0.0"

dev_dependencies:
  lint: ">=1.10.0 <3.0.0"
  test: ^1.21.6

executables:
  interactive:
