name: Post-release

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0,30 * * * *'

jobs:
  flutter:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: Mimic installation process
        run: dart pub global activate interactive

      - name: Mimic usage process
        run: echo "a=1;print(a);" | interactive

